# Generated by Django 4.2.27 on 2025-12-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='location',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.market'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.market'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('market', 'name')},
        ),
    ]
