# Generated by Django 4.2.27 on 2025-12-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_market_alter_location_name_location_market_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
