# Generated by Django 4.2.27 on 2025-12-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_location_unique_together_alter_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='password_hash',
            new_name='password',
        ),
    ]
