# Generated by Django 4.2.27 on 2025-12-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_password_hash_market_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='password',
            new_name='password_hash',
        ),
    ]
