# Generated by Django 4.2.27 on 2025-12-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_market_alter_location_name_location_market_and_more'),
        ('sales', '0003_sale_purchase_price_sale_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='market',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.market'),
            preserve_default=False,
        ),
    ]
